### ISSUE TITLE
Download DLCs (and Extras)

### ISSUE THREAD

**Issue by Hades0299** [nicohman/wyvern#1]
Great Idea, especially the delta-downloads.

There is one thing, i would like to see, and that is downloading of DLCs for the games. Downloading the Extras (Soundtrack, etc)  if available would be a nice to have, if download of DLCs is easy to implement.

**Comment by nicohman** [comment]
Good suggestion! I'll see about implementing this, though it might take a little bit.

**Comment by nicohman** [comment]
Both DLC and extras can now be downloaded, implemented in commits 5f79bda0 and b764edc1 respectively.
