### ISSUE TITLE
wyvern extras --all --id 1207666073 --output folder/

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#19]
It would be super nice to get a few extra features in the extras subcommand.

    wyvern extras --all --id 1207666073 --output folder-name

I'd like to decide both the specific game, not searching for a name, and selecting what folder to download to. This would practically fix #17 for me.

**Comment by nicohman** [comment]
Added these in da0e05d00c46ed3b15a4ca44a777e22860c70dcb and 8b281f40f286b2ffa0484f8adcabe5e9b36ee016.

**Comment by sigboe** [comment]
Great, that was quick, thanks!
