### ISSUE TITLE
Would you be able to download single extras if yo knew the slug for each of them?

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#20]
If you cold download single extras if you knew the slug, then check out the v2 api.

    curl -s https://api.gog.com/v2/games/1207658787?locale=en |  jq '._embedded | .bonuses[] | .type' 

I there are more things in the way to download a single extra, then feel free to close this issue.

**Comment by nicohman** [comment]
cb3d49840166de3543e92153c2671fbb94bdc16a should let you download extras by name with the --slug option.
