### ISSUE TITLE
login via commandline parameters

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#21]
Could you please add a way to login like so?

    wyvern login --email "${email}" --password "${password}"
Oh and the most common convention is if you don't have the `--password` parameter, you would be able to type that after, to not pollute your bash history.

Maybe 

    wyvern login --token "${token}"
should also work

**Comment by nicohman** [comment]
Added these options & subcommand in 1382c1c86b6ccbb9c5a3a6673f0af44bb11b0112

**Comment by sigboe** [comment]
Thank you one million!
