### ISSUE TITLE
Login via `login -u xxx -p xxx` does not work

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#22]
Login via `login -u xxx -p xxx` does not work. Even if I get to enter the 2FA, it just creates a empty wyvern.toml including only `version = 1`

Also happens if I delete the wyvern.toml and get past the 2FA on the first try, so it does not seam to have an issue overwriting the file.

**Comment by nicohman** [comment]
Whoops! I accidentally forgot to actually store the token with the username and password login. My bad. Should be fixed now.

**Comment by sigboe** [comment]
Thanks!!
