### ISSUE TITLE
returncodes for login errors?

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#26]
Sometimes I get errors like

```
ERROR 2019-06-18T21:09:40Z: gog::token: Login failed. Incorrect credentials
ERROR 2019-06-18T21:09:40Z: wyvern: Could not login to GOG.
ERROR 2019-06-18T21:09:40Z: wyvern: Wrong email or password. Sometimes this fails because GOG's login form can be inconsistent, so you may just need to try again.
```

Which are totally fair. I just wonder if you could add a retuncodes so I can react to them more easily.

**Comment by nicohman** [comment]
Not really, unfortunately. It’s not very possible to distinguish between the two responses, which is why it’s returned as a single error type, unlike the captcha error.
