### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by MaxMatti** [nicohman/wyvern#31]
So either I'm too stupid to use this, it's not properly documented or I am encountering a bug:
```
$ wyvern ls
It appears that you have not logged into GOG. Please pick a login method.
Login Method:
  OAuth Token Login
  Username/Password Login
```
so far so good. But as soon as I press any button, the text below `Login Method:` disappears and nothing happens anymore, also no characters that I type are displayed. Should I type something into a password field or should there appear something that doesn't?

I don't want to put my password into my bash-history, so I would prefer an interactive login method.

Distro: Archlinux
Version: `wyvern 1.4.0` - installed from AUR an hour or so ago.

**Comment by MaxMatti** [comment]
Turns out I need to use the up and down arrow keys to choose one. However in my opinion this is quite unintuitive for a command line program. I would prefer an interface similar to `yay` or at least a hint on how to use the program.

**Comment by nicohman** [comment]
Personally I decided to not have a default option so that users have to think about which login method they're thinking. I will see about changing the text to 'Please pick a login method with the arrow keys', though.

**Comment by MaxMatti** [comment]
Also pressing any key other than the arrow keys should not result in the options disappearing.
