### ISSUE TITLE
Extract installer?

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#4]
I am looking into the possibility of making a curses (or something) frontend for retropie that will download and convert dosbox games to hopefully work in retropie. 

I am currently downloading a game like this

    wyvern down --id 1207659026 --windows-auto

The resulting filename should maybe have the .exe  file ending?

I have successfully extracted an installer using innoextract which is in the raspbian (and debian) repositories like this.

    innoextract --exclude-temp  -gog filename

Is extracting the exe files something you think you would integrate into Wyvern?

**Comment by nicohman** [comment]
Yeah, this could definitely be implemented. You'd obviously need innoextract to be installed, but it could easily be done. I'll put it onto the todo list. Also, RE the naming issue: with the next major version and the current git master, downloads will preserve the default GOG names by default.

**Comment by nicohman** [comment]
Added in commit e1d4847c.

**Comment by sigboe** [comment]
For future reference:
Here is a script to unpack the linux installers https://github.com/Yepoleb/gogextract
And here is a fork of innoextract that is focused on gog installers, I did find at least one installer that does not work with innoextract https://github.com/immi101/innoextract/tree/gogextract

**Comment by nicohman** [comment]
Yeah, the current [gog extract script](https://github.com/nicohman/gog-rs/blob/master/src/extract.rs) was based on that.
