### ISSUE TITLE
Can I get some metadata from the file before download?

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#6]
Can you implement fetching some metadata before downloading?

Wishlist:
* Filesize
* Is it a dosbox game? (I don't know if this is possible)
* other metadata listed on the website

**Comment by nicohman** [comment]
You can get everything except possibly whether or not it's a dosbox game(that seems to only be available on the website itself) through the API, but at that point it really seems like it's outside of the scope of wyvern. It would be a much better suit to use the [gog crate I made for wyvern](https://crates.io/crates/gog) and write your own simple rust program using it. Is there a specific reason you need wyvern to provide this metadata?

**Comment by sigboe** [comment]
Is it possible to get the text in the system requirements? If so it should be possible to search for DosBOX.

**Comment by nicohman** [comment]
It doesn't appear so. The system requirements are only available when they're served directly on the store page for the product--they aren't retrieved via an API like almost everything else.

**Comment by sigboe** [comment]
Is it possible to get the website url for the game?

**Comment by nicohman** [comment]
Yup. That's returned by both of the filtered_products endpoints [as url](https://docs.rs/gog/0.3.1/gog/gog/struct.ProductDetails.html). Once you have that, it's easy to use a HTML parser to interpret the page and look for an element with the class dosbox-info.

**Comment by nicohman** [comment]
Additional metadata added from issue #7.

**Comment by sigboe** [comment]
Thanks

**Comment by sigboe** [comment]
@nicohman  fro future refrence, here is how to read the description

    http://api.gog.com/products/1207659026?expand=description

It does not require login or authentication
