### ISSUE TITLE
Being able to set a path/filename for downloads would be great

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#9]
Being able to decide where to download, and decide an output filename would be great.
Example:

    wyvern down --id 1234 -o ~/Downloads/ #I just want to pick a folder
    wyvern down --id 1234 -o ~/Downloads/myfilename.exe #I want to pick a fully qualified name

Being able to perserve the fileextension if you didnt pick one or using a flag would be even greater

    wyvern down --id 1207659026 -o ~/Downloads/Theme\ Hospital/1207659026 --preserve-fileextension
    #I want t pick a folder and a name, but I don't want to care about the extension.

**Comment by nicohman** [comment]
Added both of these options in commit b81db26. Note: If multiple files are downloaded, it appends a counter to the end of each file's name.
